<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/createinvoice_REQUEST/types" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/test_REQUEST/types" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora nssrcmpr oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr1 nsmpr2 nsmpr3 nsmpr1 ns27 nsmpr3 fn ns27 nsmpr3" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/REST/test/types" xmlns:ns21="http://xmlns.oracle.com/cloud/adapter/REST/createinvoice/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/stagefile/test1_REQUEST/types" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/stagefile/test1r_REQUEST/types" xmlns:ns27="http://xmlns.oracle.com/cloud/adapter/stagefile/test1r/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/test_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/test_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_21">
            <oracle-xsl-mapper:schema location="../../processor_37/resourcegroup_44/generated.wsdl" xml:id="id_22"/>
            <oracle-xsl-mapper:rootElement name="apInvoiceRequest" namespace="http://xmlns.oracle.com/cloud/adapter/REST/test/types" xml:id="id_23"/>
            <oracle-xsl-mapper:param name="currInvoice" xml:id="id_24"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_111">
            <oracle-xsl-mapper:schema location="../../processor_134/resourcegroup_135/test1r_REQUEST.wsdl" xml:id="id_112"/>
            <oracle-xsl-mapper:rootElement name="ReadResponse" namespace="http://xmlns.oracle.com/cloud/adapter/stagefile/test1r_REQUEST/types" xml:id="id_113"/>
            <oracle-xsl-mapper:param name="test1r" xml:id="id_114"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_20/inbound_21/resourcegroup_22/createinvoice_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/createinvoice_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="currInvoice" xml:id="id_25"/>
   <xsl:param name="test1r" xml:id="id_118"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:execute xml:id="id_12">
         <ns21:request-wrapper xml:id="id_26">
            <ns21:InvoiceNumber xml:id="id_27">
               <xsl:value-of xml:id="id_28" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:InvoiceNumber"/>
            </ns21:InvoiceNumber>
            <ns21:InvoiceType xml:id="id_29">
               <xsl:value-of xml:id="id_30" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:InvoiceType"/>
            </ns21:InvoiceType>
            <ns21:InvoiceCurrency xml:id="id_31">
               <xsl:value-of xml:id="id_32" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:InvoiceCurrency"/>
            </ns21:InvoiceCurrency>
            <ns21:PaymentCurrency xml:id="id_33">
               <xsl:value-of xml:id="id_34" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:PaymentCurrency"/>
            </ns21:PaymentCurrency>
            <ns21:InvoiceAmount xml:id="id_124">
               <xsl:value-of xml:id="id_125" select="sum ($test1r/nsmpr3:ReadResponse/ns27:request-wrapper/ns27:amount/ns27:lineamount )"/>
            </ns21:InvoiceAmount>
            <ns21:InvoiceDate xml:id="id_35">
               <xsl:value-of xml:id="id_36" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:InvoiceDate"/>
            </ns21:InvoiceDate>
            <ns21:AccountingDate xml:id="id_37">
               <xsl:value-of xml:id="id_38" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:AccountingDate"/>
            </ns21:AccountingDate>
            <ns21:BusinessUnit xml:id="id_39">
               <xsl:value-of xml:id="id_40" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:BusinessUnit"/>
            </ns21:BusinessUnit>
            <ns21:Supplier xml:id="id_41">
               <xsl:value-of xml:id="id_42" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:Supplier"/>
            </ns21:Supplier>
            <ns21:SupplierSite xml:id="id_43">
               <xsl:value-of xml:id="id_44" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:SupplierSite"/>
            </ns21:SupplierSite>
            <ns21:InvoiceGroup xml:id="id_45">
               <xsl:value-of xml:id="id_46" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:InvoiceGroup"/>
            </ns21:InvoiceGroup>
            <ns21:Description xml:id="id_47">
               <xsl:value-of xml:id="id_48" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:Description"/>
            </ns21:Description>
            <ns21:PaymentTerms xml:id="id_49">
               <xsl:value-of xml:id="id_50" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:PaymentTerms"/>
            </ns21:PaymentTerms>
            <ns21:TermsDate xml:id="id_51">
               <xsl:value-of xml:id="id_52" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:TermsDate"/>
            </ns21:TermsDate>
            <ns21:PurchaseOrderNumber xml:id="id_53">
               <xsl:value-of xml:id="id_54" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:PurchaseOrderNumber"/>
            </ns21:PurchaseOrderNumber>
            <ns21:LiabilityDistribution xml:id="id_55">
               <xsl:value-of xml:id="id_56" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:LiabilityDistribution"/>
            </ns21:LiabilityDistribution>
            <xsl:for-each xml:id="id_58" select="$currInvoice/nsmpr1:apInvoiceRequest/nsmpr1:invoiceLines">
               <ns21:invoiceLines xml:id="id_59">
                  <ns21:LineNumber xml:id="id_60">
                     <xsl:value-of xml:id="id_61" select="nsmpr1:LineNumber"/>
                  </ns21:LineNumber>
                  <ns21:LineAmount xml:id="id_122">
                     <xsl:value-of xml:id="id_123" select="number (nsmpr1:Quantity ) * number (nsmpr1:UnitPrice )"/>
                  </ns21:LineAmount>
                  <ns21:Description xml:id="id_64">
                     <xsl:value-of xml:id="id_65" select="nsmpr1:Description"/>
                  </ns21:Description>
                  <ns21:Quantity xml:id="id_66">
                     <xsl:value-of xml:id="id_67" select="nsmpr1:Quantity"/>
                  </ns21:Quantity>
                  <ns21:UnitPrice xml:id="id_68">
                     <xsl:value-of xml:id="id_69" select="nsmpr1:UnitPrice"/>
                  </ns21:UnitPrice>
                  <ns21:PurchaseOrderNumber xml:id="id_70">
                     <xsl:value-of xml:id="id_71" select="nsmpr1:PurchaseOrderNumber"/>
                  </ns21:PurchaseOrderNumber>
                  <ns21:PurchaseOrderLineNumber xml:id="id_72">
                     <xsl:value-of xml:id="id_73" select="nsmpr1:PurchaseOrderLineNumber"/>
                  </ns21:PurchaseOrderLineNumber>
                  <ns21:PurchaseOrderScheduleLineNumber xml:id="id_74">
                     <xsl:value-of xml:id="id_75" select="nsmpr1:PurchaseOrderScheduleLineNumber"/>
                  </ns21:PurchaseOrderScheduleLineNumber>
               </ns21:invoiceLines>
            </xsl:for-each>
         </ns21:request-wrapper>
      </nstrgmpr:execute>
   </xsl:template>
</xsl:stylesheet>