<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/item_REQUEST/getItem/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/REST/getItems_REQUEST/types" xmlns:nsmpr1="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns22="http://xmlns.oracle.com/cloud/adapter/REST/item/getItem/types" xmlns:ns30="http://xmlns.oracle.com/cloud/adapter/REST/getItems/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_69/outbound_70/resourcegroup_71/item_getItem_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/item_REQUEST/getItem/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_13">
            <oracle-xsl-mapper:schema location="../../application_102/inbound_103/resourcegroup_104/getItems_REQUEST.wsdl" xml:id="id_14"/>
            <oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/getItems_REQUEST/types" xml:id="id_15"/>
            <oracle-xsl-mapper:param name="getItems" xml:id="id_16"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_69/outbound_70/resourcegroup_71/item_getItem_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/item_REQUEST/getItem/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="getItems" xml:id="id_28"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:executeResponse xml:id="id_12">
         <ns22:response-wrapper xml:id="id_31">
            <xsl:for-each xml:id="id_33" select="$getItems/nsmpr0:executeResponse/ns30:response-wrapper/ns30:items">
               <ns22:items xml:id="id_34">
                  <ns22:ItemId xml:id="id_46">
                     <xsl:value-of xml:id="id_47" select="ns30:ItemId"/>
                  </ns22:ItemId>
                  <ns22:OrganizationCode xml:id="id_48">
                     <xsl:value-of xml:id="id_49" select="ns30:OrganizationCode"/>
                  </ns22:OrganizationCode>
                  <ns22:ItemClass xml:id="id_50">
                     <xsl:value-of xml:id="id_51" select="ns30:ItemClass"/>
                  </ns22:ItemClass>
                  <ns22:ItemNumber xml:id="id_52">
                     <xsl:value-of xml:id="id_53" select="ns30:ItemNumber"/>
                  </ns22:ItemNumber>
                  <ns22:ItemStatusValue xml:id="id_54">
                     <xsl:value-of xml:id="id_55" select="ns30:ItemStatusValue"/>
                  </ns22:ItemStatusValue>
                  <ns22:PrimaryUOMValue xml:id="id_56">
                     <xsl:value-of xml:id="id_57" select="ns30:PrimaryUOMValue"/>
                  </ns22:PrimaryUOMValue>
               </ns22:items>
            </xsl:for-each>
            <ns22:count xml:id="id_35">
               <xsl:value-of xml:id="id_36" select="$getItems/nsmpr0:executeResponse/ns30:response-wrapper/ns30:count"/>
            </ns22:count>
            <ns22:hasMore xml:id="id_37">
               <xsl:value-of xml:id="id_38" select="$getItems/nsmpr0:executeResponse/ns30:response-wrapper/ns30:hasMore"/>
            </ns22:hasMore>
            <ns22:limit xml:id="id_44">
               <xsl:value-of xml:id="id_45" select="$getItems/nsmpr0:executeResponse/ns30:response-wrapper/ns30:limit"/>
            </ns22:limit>
            <ns22:offset xml:id="id_39">
               <xsl:value-of xml:id="id_40" select="$getItems/nsmpr0:executeResponse/ns30:response-wrapper/ns30:offset"/>
            </ns22:offset>
            <xsl:for-each xml:id="id_42" select="$getItems/nsmpr0:executeResponse/ns30:response-wrapper/ns30:links">
               <ns22:links xml:id="id_43"/>
            </xsl:for-each>
         </ns22:response-wrapper>
      </nstrgmpr:executeResponse>
   </xsl:template>
</xsl:stylesheet>