<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeDepartment_REQUEST/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext nssrcmpr xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployee_REQUEST/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeNumber_REQUEST/types" xmlns:nsmpr2="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns17="http://xmlns.oracle.com/cloud/adapter/REST/employee/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/employee_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_59">
            <oracle-xsl-mapper:schema location="../../processor_111/resourcegroup_118/generated.wsdl" xml:id="id_60"/>
            <oracle-xsl-mapper:rootElement name="Employes" namespace="http://xmlns.oracle.com/cloud/adapter/REST/employee/types" xml:id="id_61"/>
            <oracle-xsl-mapper:param name="currEmployee" xml:id="id_62"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_77">
            <oracle-xsl-mapper:schema location="../../application_75/inbound_76/resourcegroup_77/atpSelectEmployee_REQUEST.wsdl" xml:id="id_78"/>
            <oracle-xsl-mapper:rootElement name="EmployeeCollection" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployee_REQUEST/types" xml:id="id_79"/>
            <oracle-xsl-mapper:param name="atpSelectEmployee" xml:id="id_80"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_81">
            <oracle-xsl-mapper:schema location="../../application_37/inbound_38/resourcegroup_39/atpSelectEmployeeNumber_REQUEST.wsdl" xml:id="id_82"/>
            <oracle-xsl-mapper:rootElement name="EmployeeCollection" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeNumber_REQUEST/types" xml:id="id_83"/>
            <oracle-xsl-mapper:param name="atpSelectEmployeeNumber" xml:id="id_84"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_85">
            <oracle-xsl-mapper:schema location="../../application_37/inbound_38/resourcegroup_39/atpSelectEmployeeNumber_REQUEST.wsdl" xml:id="id_86"/>
            <oracle-xsl-mapper:rootElement name="atpSelectEmployeeNumberSelect_EmployeeNumberInputParameters" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeNumber_REQUEST/types" xml:id="id_87"/>
            <oracle-xsl-mapper:param name="atpSelectEmployeeNumber_REQUEST" xml:id="id_88"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_89">
            <oracle-xsl-mapper:schema location="../../application_75/inbound_76/resourcegroup_77/atpSelectEmployee_REQUEST.wsdl" xml:id="id_90"/>
            <oracle-xsl-mapper:rootElement name="atpSelectEmployeeSelectInputParameters" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployee_REQUEST/types" xml:id="id_91"/>
            <oracle-xsl-mapper:param name="atpSelectEmployee_REQUEST" xml:id="id_92"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_93">
            <oracle-xsl-mapper:schema location="../../processor_1/resourcegroup_2/ICSIntegrationMetadata.xsd" xml:id="id_94"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_95"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_96"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_92/inbound_93/resourcegroup_94/atpSelectEmployeeDepartment_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="atpSelectEmployeeDepartmentSelect_DepartmentNameInputParameters" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeDepartment_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="currEmployee" xml:id="id_71"/>
   <xsl:param name="atpSelectEmployee" xml:id="id_97"/>
   <xsl:param name="atpSelectEmployeeNumber" xml:id="id_98"/>
   <xsl:param name="atpSelectEmployeeNumber_REQUEST" xml:id="id_99"/>
   <xsl:param name="atpSelectEmployee_REQUEST" xml:id="id_100"/>
   <xsl:param name="self" xml:id="id_101"/>
   <xsl:param name="tracking_var_1" xml:id="id_102"/>
   <xsl:param name="tracking_var_2" xml:id="id_103"/>
   <xsl:param name="tracking_var_3" xml:id="id_104"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:atpSelectEmployeeDepartmentSelect_DepartmentNameInputParameters xml:id="id_12">
         <nstrgmpr:DepartmentName xml:id="id_41">
            <xsl:value-of xml:id="id_76" select="$currEmployee/ns17:Employes/ns17:Department/ns17:DepartmentName"/>
         </nstrgmpr:DepartmentName>
      </nstrgmpr:atpSelectEmployeeDepartmentSelect_DepartmentNameInputParameters>
   </xsl:template>
</xsl:stylesheet>