<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://www.oracle.com/2014/03/ics/schedule" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/ftp/moveToErrorFolderFTP_REQUEST/types" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 fn nsmpr0 nsmpr0 fn" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/list/pull" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/ftp/listFilesFTP_REQUEST/types" xmlns:nsmpr2="http://www.oracle.com/2014/03/ics/fault" xmlns:nsmpr3="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns20="http://xmlns.oracle.com/ics/cloud/ftp/move/pull">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="XSD" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../processor_8/resourcegroup_9/ICSSchedule_1.xsd" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="schedule" namespace="http://www.oracle.com/2014/03/ics/schedule" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_13">
            <oracle-xsl-mapper:schema location="../../processor_38/resourcegroup_45/generated.wsdl" xml:id="id_14"/>
            <oracle-xsl-mapper:rootElement name="File" namespace="http://xmlns.oracle.com/cloud/list/pull" xml:id="id_15"/>
            <oracle-xsl-mapper:param name="currFile" xml:id="id_16"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_224/inbound_225/resourcegroup_226/moveToErrorFolderFTP_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="MoveFile" namespace="http://xmlns.oracle.com/cloud/adapter/ftp/moveToErrorFolderFTP_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="currFile" xml:id="id_33"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:MoveFile xml:id="id_12">
         <ns20:FileMoveRequest xml:id="id_41">
            <ns20:directory xml:id="id_42">
               <xsl:value-of xml:id="id_43" select="$currFile/nsmpr0:File/nsmpr0:directory"/>
            </ns20:directory>
            <ns20:filename xml:id="id_44">
               <xsl:value-of xml:id="id_45" select="$currFile/nsmpr0:File/nsmpr0:filename"/>
            </ns20:filename>
            <ns20:targetDirectory xml:id="id_46">
               <xsl:value-of xml:id="id_47" select="&quot;/home/users/integration@knextech.com/Internal/Project/SM/Error&quot;"/>
            </ns20:targetDirectory>
            <ns20:targetFilename xml:id="id_48">
               <xsl:value-of xml:id="id_49" select="concat (&quot;Error_&quot;, fn:current-date(), &quot;_&quot;, $currFile/nsmpr0:File/nsmpr0:filename )"/>
            </ns20:targetFilename>
         </ns20:FileMoveRequest>
      </nstrgmpr:MoveFile>
   </xsl:template>
</xsl:stylesheet>