<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/createInvoice_REQUEST/types" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/ReceiveEventPayload_REQUEST/types" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora nssrcmpr oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns25="http://xmlns.oracle.com/cloud/adapter/REST/createInvoice/types" xmlns:ns20="http://xmlns.oracle.com/cloud/adapter/REST/ReceiveEventPayload/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/ReceiveEventPayload_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/ReceiveEventPayload_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_36/inbound_37/resourcegroup_38/createInvoice_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/createInvoice_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:execute xml:id="id_12">
         <ns25:request-wrapper xml:id="id_21">
            <ns25:InvoiceNumber xml:id="id_22">
               <xsl:value-of xml:id="id_23" select="/nssrcmpr:execute/ns20:request-wrapper/ns20:InvoiceNumber"/>
            </ns25:InvoiceNumber>
            <ns25:InvoiceCurrency xml:id="id_24">
               <xsl:value-of xml:id="id_25" select="/nssrcmpr:execute/ns20:request-wrapper/ns20:InvoiceCurrency"/>
            </ns25:InvoiceCurrency>
            <ns25:InvoiceAmount xml:id="id_26">
               <xsl:value-of xml:id="id_27" select="/nssrcmpr:execute/ns20:request-wrapper/ns20:InvoiceAmount"/>
            </ns25:InvoiceAmount>
            <ns25:InvoiceDate xml:id="id_28">
               <xsl:value-of xml:id="id_29" select="/nssrcmpr:execute/ns20:request-wrapper/ns20:InvoiceDate"/>
            </ns25:InvoiceDate>
            <ns25:BusinessUnit xml:id="id_30">
               <xsl:value-of xml:id="id_31" select="/nssrcmpr:execute/ns20:request-wrapper/ns20:BusinessUnit"/>
            </ns25:BusinessUnit>
            <ns25:Supplier xml:id="id_32">
               <xsl:value-of xml:id="id_33" select="/nssrcmpr:execute/ns20:request-wrapper/ns20:Supplier"/>
            </ns25:Supplier>
            <ns25:SupplierSite xml:id="id_36">
               <xsl:value-of xml:id="id_37" select="/nssrcmpr:execute/ns20:request-wrapper/ns20:SupplierSite"/>
            </ns25:SupplierSite>
            <ns25:InvoiceGroup xml:id="id_34">
               <xsl:value-of xml:id="id_35" select="/nssrcmpr:execute/ns20:request-wrapper/ns20:InvoiceGroup"/>
            </ns25:InvoiceGroup>
            <ns25:Description xml:id="id_41">
               <xsl:value-of xml:id="id_42" select="/nssrcmpr:execute/ns20:request-wrapper/ns20:Description"/>
            </ns25:Description>
            <xsl:for-each xml:id="id_39" select="/nssrcmpr:execute/ns20:request-wrapper/ns20:invoiceLines">
               <ns25:invoiceLines xml:id="id_40">
                  <ns25:LineNumber xml:id="id_45">
                     <xsl:value-of xml:id="id_46" select="ns20:LineNumber"/>
                  </ns25:LineNumber>
                  <ns25:LineAmount xml:id="id_47">
                     <xsl:value-of xml:id="id_48" select="ns20:LineAmount"/>
                  </ns25:LineAmount>
                  <ns25:AccountingDate xml:id="id_49">
                     <xsl:value-of xml:id="id_50" select="ns20:AccountingDate"/>
                  </ns25:AccountingDate>
                  <ns25:DistributionCombination xml:id="id_43">
                     <xsl:value-of xml:id="id_44" select="ns20:DistributionCombination"/>
                  </ns25:DistributionCombination>
               </ns25:invoiceLines>
            </xsl:for-each>
         </ns25:request-wrapper>
      </nstrgmpr:execute>
   </xsl:template>
</xsl:stylesheet>