<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/getEmployee/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployee_REQUEST/types" xmlns:nsmpr1="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns24="http://xmlns.oracle.com/cloud/adapter/REST/employee/getEmployee/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_10/outbound_11/resourcegroup_12/employee_getEmployee_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/getEmployee/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_13">
            <oracle-xsl-mapper:schema location="../../application_54/inbound_55/resourcegroup_56/atpSelectEmployee_REQUEST.wsdl" xml:id="id_14"/>
            <oracle-xsl-mapper:rootElement name="EmployeeCollection" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployee_REQUEST/types" xml:id="id_15"/>
            <oracle-xsl-mapper:param name="atpSelectEmployee" xml:id="id_16"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_10/outbound_11/resourcegroup_12/employee_getEmployee_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/getEmployee/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="atpSelectEmployee" xml:id="id_25"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:executeResponse xml:id="id_12">
         <ns24:response-wrapper xml:id="id_34">
            <ns24:Result xml:id="id_35">
               <xsl:value-of xml:id="id_36" select="concat (&quot;Success retrieve employee detail from employee number &quot;, /nstrgmpr:execute/ns24:request-wrapper/ns24:EmployeeNumber )"/>
            </ns24:Result>
            <ns24:EmployeeNumber xml:id="id_37">
               <xsl:value-of xml:id="id_38" select="$atpSelectEmployee/nsmpr0:EmployeeCollection/nsmpr0:Employee/nsmpr0:employeeNumber"/>
            </ns24:EmployeeNumber>
            <ns24:EmployeeName xml:id="id_39">
               <xsl:value-of xml:id="id_40" select="$atpSelectEmployee/nsmpr0:EmployeeCollection/nsmpr0:Employee/nsmpr0:employeeName"/>
            </ns24:EmployeeName>
            <ns24:EmployeeEmail xml:id="id_41">
               <xsl:value-of xml:id="id_42" select="$atpSelectEmployee/nsmpr0:EmployeeCollection/nsmpr0:Employee/nsmpr0:employeeEmail"/>
            </ns24:EmployeeEmail>
            <ns24:Status xml:id="id_43">
               <xsl:value-of xml:id="id_44" select="$atpSelectEmployee/nsmpr0:EmployeeCollection/nsmpr0:Employee/nsmpr0:status"/>
            </ns24:Status>
         </ns24:response-wrapper>
      </nstrgmpr:executeResponse>
   </xsl:template>
</xsl:stylesheet>