<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpMergeEmployee_REQUEST/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext nssrcmpr xsi xsd fn xp20 xsl ignore01 nsmpr0" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns15="http://xmlns.oracle.com/cloud/adapter/REST/employee/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/employee_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_38/inbound_39/resourcegroup_40/atpMergeEmployee_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpMergeEmployee_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:InputParameters xml:id="id_12">
         <nstrgmpr:P_EMPLOYEE_NUMBER xml:id="id_21">
            <xsl:value-of xml:id="id_22" select="/nssrcmpr:execute/ns15:request-wrapper/ns15:Employes/ns15:EmployeeNumber"/>
         </nstrgmpr:P_EMPLOYEE_NUMBER>
         <nstrgmpr:P_EMPLOYEE_NAME xml:id="id_23">
            <xsl:value-of xml:id="id_24" select="/nssrcmpr:execute/ns15:request-wrapper/ns15:Employes/ns15:EmployeeName"/>
         </nstrgmpr:P_EMPLOYEE_NAME>
         <nstrgmpr:P_EMPLOYEE_EMAIL xml:id="id_25">
            <xsl:value-of xml:id="id_26" select="/nssrcmpr:execute/ns15:request-wrapper/ns15:Employes/ns15:EmployeeEmail"/>
         </nstrgmpr:P_EMPLOYEE_EMAIL>
         <nstrgmpr:P_EMPLOYEE_STATUS xml:id="id_27">
            <xsl:value-of xml:id="id_28" select="/nssrcmpr:execute/ns15:request-wrapper/ns15:Employes/ns15:Status"/>
         </nstrgmpr:P_EMPLOYEE_STATUS>
         <nstrgmpr:P_DEPARTMENT_NUMBER xml:id="id_31">
            <xsl:value-of xml:id="id_32" select="/nssrcmpr:execute/ns15:request-wrapper/ns15:Employes/ns15:Department/ns15:DepartmentNumber"/>
         </nstrgmpr:P_DEPARTMENT_NUMBER>
         <nstrgmpr:P_DEPARTMENT_NAME xml:id="id_29">
            <xsl:value-of xml:id="id_30" select="/nssrcmpr:execute/ns15:request-wrapper/ns15:Employes/ns15:Department/ns15:DepartmentName"/>
         </nstrgmpr:P_DEPARTMENT_NAME>
         <nstrgmpr:P_DEPARTMENT_STATUS xml:id="id_33">
            <xsl:value-of xml:id="id_34" select="/nssrcmpr:execute/ns15:request-wrapper/ns15:Employes/ns15:Department/ns15:Status"/>
         </nstrgmpr:P_DEPARTMENT_STATUS>
         <nstrgmpr:P_LOCATION_NUMBER xml:id="id_35">
            <xsl:value-of xml:id="id_36" select="/nssrcmpr:execute/ns15:request-wrapper/ns15:Employes/ns15:Department/ns15:Location/ns15:LocationNumber"/>
         </nstrgmpr:P_LOCATION_NUMBER>
         <nstrgmpr:P_LOCATION_NAME xml:id="id_39">
            <xsl:value-of xml:id="id_40" select="/nssrcmpr:execute/ns15:request-wrapper/ns15:Employes/ns15:Department/ns15:Location/ns15:LocationName"/>
         </nstrgmpr:P_LOCATION_NAME>
         <nstrgmpr:P_LOCATION_STATUS xml:id="id_37">
            <xsl:value-of xml:id="id_38" select="/nssrcmpr:execute/ns15:request-wrapper/ns15:Employes/ns15:Department/ns15:Location/ns15:Status"/>
         </nstrgmpr:P_LOCATION_STATUS>
      </nstrgmpr:InputParameters>
   </xsl:template>
</xsl:stylesheet>