<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/insertEmployee/types" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpInsertEmployee_REQUEST/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm nssrcmpr oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/REST/employee/insertEmployee/types" xmlns:nsmpr1="http://www.oracle.com/2014/03/ic/integration/metadata">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_32/outbound_33/resourcegroup_34/employee_insertEmployee_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/insertEmployee/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_13">
            <oracle-xsl-mapper:schema location="../../processor_86/resourcegroup_93/generated.wsdl" xml:id="id_14"/>
            <oracle-xsl-mapper:rootElement name="Employes" namespace="http://xmlns.oracle.com/cloud/adapter/REST/employee/insertEmployee/types" xml:id="id_15"/>
            <oracle-xsl-mapper:param name="currEmployee" xml:id="id_16"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_71/inbound_72/resourcegroup_73/atpInsertEmployee_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="EmployeeCollection" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpInsertEmployee_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="currEmployee" xml:id="id_21"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:EmployeeCollection xml:id="id_12">
         <nstrgmpr:Employee xml:id="id_26">
            <nstrgmpr:id xml:id="id_45">
               <xsl:value-of xml:id="id_46" select="$currEmployee/nsmpr0:Employes/nsmpr0:Id"/>
            </nstrgmpr:id>
            <nstrgmpr:employeeNumber xml:id="id_27">
               <xsl:value-of xml:id="id_28" select="$currEmployee/nsmpr0:Employes/nsmpr0:EmployeeNumber"/>
            </nstrgmpr:employeeNumber>
            <nstrgmpr:employeeName xml:id="id_31">
               <xsl:value-of xml:id="id_32" select="$currEmployee/nsmpr0:Employes/nsmpr0:EmployeeName"/>
            </nstrgmpr:employeeName>
            <nstrgmpr:employeeEmail xml:id="id_29">
               <xsl:value-of xml:id="id_30" select="$currEmployee/nsmpr0:Employes/nsmpr0:EmployeeEmail"/>
            </nstrgmpr:employeeEmail>
            <nstrgmpr:departmentNumber xml:id="id_33">
               <xsl:value-of xml:id="id_34" select="$currEmployee/nsmpr0:Employes/nsmpr0:Department/nsmpr0:DepartmentNumber"/>
            </nstrgmpr:departmentNumber>
            <nstrgmpr:status xml:id="id_35">
               <xsl:value-of xml:id="id_36" select="$currEmployee/nsmpr0:Employes/nsmpr0:Status"/>
            </nstrgmpr:status>
         </nstrgmpr:Employee>
      </nstrgmpr:EmployeeCollection>
   </xsl:template>
</xsl:stylesheet>