---
id: KNEX_TRAINI___PROJEC
code: KNEX_TRAINI___PROJEC
name: KNEX Training - Project
type: DEVELOPED
smartTags:
- "app:soap, app:ftp,style:scheduled orchestration"
- style:scheduled orchestration
- "app:rest, app:erp,style:app driven orchestration"
- "app:appevent,style:subscribed orchestration"
- style:app driven orchestration
- "app:rest, app:ftp,style:scheduled orchestration"
- "app:atpdatabase,style:app driven orchestration"
- "app:oracle:github,style:scheduled orchestration"
- "app:rest, app:appevent,style:app driven orchestration"
- "app:ftp, app:erp,style:app driven orchestration"
- "app:rest,style:app driven orchestration"
- "app:rest, app:atpdatabase,style:app driven orchestration"
- "app:rest, app:soap, app:ftp,style:app driven orchestration"
- "app:ftp, app:rest,style:app driven orchestration"
- "app:ftp,style:scheduled orchestration"
- "app:ftp,style:app driven orchestration"
revision: 0
projectRevision: 8308
status: DRAFT
createdBy: syusop@knextech.com
createdDate: 2024-06-14T03:44:26.486+0000
updatedBy: syusop@knextech.com
updatedDate: 2024-06-14T03:44:26.486+0000
latestBy: cychew@knextech.com
latestDate: 2024-08-27T07:13:26.609+0000
CAV: 1
assets:
  integrations:
  - id: AI_LOGIC|01.00.0000
    name: AI Logic
    revision: 9
    updatedBy: vbcsuser2@knextech.com
    updatedDate: 2024-08-27T06:02:39.401+0000
  - id: AZ_EMPLOYEE|01.00.0000
    name: AZ Employee
    revision: 0
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-17T04:40:24.438+0000
  - id: AZ_EMPLOYEE_MERGE|01.00.0000
    name: AZ Employee Merge
    revision: 3
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-20T08:27:44.478+0000
  - id: AZ_EMPLOYEE_SP|01.00.0000
    name: AZ Employee SP
    revision: 4
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-20T07:28:31.677+0000
  - id: AZ_JAVASCRIPT|01.00.0000
    name: AZ Javascript
    revision: 72
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-27T01:17:28.777+0000
  - id: AZ_JAVASCRIPT_CONDITION|01.00.0000
    name: AZ Javascript Condition
    revision: 7
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-27T03:38:21.613+0000
  - id: AZ_JAVASCRIPT_DATE|01.00.0000
    name: AZ Javascript date
    revision: 44
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-27T00:23:01.030+0000
  - id: AZ_JAVASCRIPT_STRING|01.00.0000
    name: AZ Javascript string
    revision: 34
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-27T00:38:09.751+0000
  - id: AZ_VIEW_EMPLOYEE|01.00.0000
    name: AZ View Employee
    revision: 5
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-20T06:25:23.809+0000
  - id: CREATE_AP_INVOICE|01.00.0000
    name: Create AP Invoice
    revision: 4
    updatedBy: syusop@knextech.com
    updatedDate: 2024-07-17T03:22:32.359+0000
  - id: CY_AMOUNT_CALCULATIO|01.00.0000
    name: CY Amount Calculation
    revision: 24
    updatedBy: cychew@knextech.com
    updatedDate: 2024-08-13T02:01:40.784+0000
  - id: CY_EMPLOYEE|01.00.0000
    name: CY Employee
    revision: 41
    updatedBy: cychew@knextech.com
    updatedDate: 2024-08-17T06:40:37.213+0000
  - id: CY_MAPPING_TEST|01.00.0000
    name: CY Mapping Test
    revision: 90
    updatedBy: cychew@knextech.com
    updatedDate: 2024-08-27T06:04:07.777+0000
  - id: ERROR_EVENT|01.00.0000
    name: Error Event
    revision: 2
    updatedBy: syusop@knextech.com
    updatedDate: 2024-07-06T06:40:24.764+0000
  - id: HELLO_SY|01.00.0000
    name: Hello SY
    revision: 59
    updatedBy: syusop@knextech.com
    updatedDate: 2024-08-27T06:04:36.937+0000
  - id: HELLO_WORLD|01.00.0000
    name: Hello World
    revision: 2
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-19T07:44:38.269+0000
  - id: IMPORT_CUSTOMERS|01.00.0000
    name: KNX Import Customers
    revision: 5
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-06-22T07:22:05.080+0000
  - id: KNEX_READ_WORKDAY_FILES|01.00.0000
    name: KNEX Read Workday Files
    revision: 1
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-20T00:54:18.190+0000
  - id: KNX_CREATE_AP_INVOICE|01.00.0000
    name: KNX Create AP Invoice
    revision: 3
    updatedBy: cychew@knextech.com
    updatedDate: 2024-07-23T08:08:54.473+0000
  - id: KNX_CREATE_CONTACT|01.00.0000
    name: KNX Create Contact
    revision: 38
    updatedBy: syusop@knextech.com
    updatedDate: 2024-07-17T03:33:42.218+0000
  - id: KNX_DOWNLOAD_AR_REPORT|01.00.0000
    name: KNX Download AR Report
    revision: 3
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-20T02:52:09.627+0000
  - id: KNX_GET_BOM_STRUCTUR|01.00.0000
    name: KNX Get BOM Structures
    revision: 2
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-20T03:32:48.502+0000
  - id: KNX_GET_ITEMS|01.00.0000
    name: KNX Get Items
    revision: 1
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-15T07:02:26.350+0000
  - id: KNX_IMPORT_AP_INVOICE|01.00.0000
    name: KNX Import AP Invoice
    revision: 2
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-20T03:34:14.364+0000
  - id: KNX_UPDATE_BOM|01.00.0000
    name: KNX Update BOM
    revision: 3
    updatedBy: cychew@knextech.com
    updatedDate: 2024-07-23T08:19:38.041+0000
  - id: NA_CONNECT_GITHUB|01.00.0000
    name: NA Connect Github
    revision: 26
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-27T07:13:43.350+0000
  - id: NA_DATE_CONVERSI_JS|01.00.0000
    name: NA Date Conversion js
    revision: 9
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-21T08:31:48.754+0000
  - id: NA_EMPLOYEE|01.00.0000
    name: NA Employee
    revision: 11
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-17T07:34:20.743+0000
  - id: NA_INVOKE_EMPLOYEE|01.00.0000
    name: NA Invoke Employee
    revision: 1
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-20T02:06:30.563+0000
  - id: NA_INVOKE_STORE_PROCED_EMPLOY|01.00.0000
    name: NA Invoke Store Procedure Employee
    revision: 3
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-20T08:32:32.967+0000
  - id: NA_MERGE_2_ARRAY|01.00.0000
    name: NA Merge 2 Array
    revision: 12
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-24T03:44:26.883+0000
  - id: NA___GENER_ID_JS|01.00.0000
    name: NA - Generate Id js
    revision: 19
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-21T03:07:31.403+0000
  - id: POC_ENCRYPT_EMAIL|01.00.0000
    name: POC Encrypt Email
    revision: 1
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-15T06:52:06.922+0000
  - id: RETRI_ALL_CODE_INFO_BY_NAME|01.00.0000
    name: Retrieve All Code Info By Name
    revision: 1
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-20T00:53:16.059+0000
  - id: SEND_AP_INVOICE|01.00.0000
    name: Send AP Invoice
    revision: 8
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-07-05T02:24:01.455+0000
  - id: SM_BASIC_JS|01.00.0000
    name: SM Basic Js
    revision: 0
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-24T02:12:44.977+0000
  - id: SM_BASIC_MATH_JS|01.00.0000
    name: SM Basic Math Js
    revision: 1
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-24T02:14:47.278+0000
  - id: SM_DATE_CONVERSI_JS|01.00.0000
    name: SM Date Conversion Js
    revision: 14
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-24T04:52:29.395+0000
  - id: SM_EMPLOYEE|01.00.0000
    name: SM Employee
    revision: 25
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-17T04:04:48.357+0000
  - id: SM_EMPLOYEE|02.00.0000
    name: SM Employee
    revision: 3
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-20T01:58:46.198+0000
  - id: SM_EMPLOYEE_MERGE|01.00.0000
    name: SM Employee Merge
    revision: 5
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-20T08:15:54.301+0000
  - id: SM_EMPLOYEE_STORED_PROCEDUR|01.00.0000
    name: SM Employee Stored Procedure
    revision: 4
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-20T07:32:24.918+0000
  - id: SM_INPUT_DETECTOR|01.00.0000
    name: SM Input Detector
    revision: 17
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-03T04:15:50.967+0000
  - id: SM_MULTIPLE_ATP_METHOD|01.00.0000
    name: SM Multiple ATP method
    revision: 4
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-21T07:37:22.654+0000
  - id: SM_POC_FAULT_HANDLER|01.00.0000
    name: SM POC Fault Handler
    revision: 24
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-09T04:42:28.154+0000
  - id: SM_POC_FAULT_HANDLER|02.00.0000
    name: SM POC Fault Handler
    revision: 2
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-09T05:07:43.893+0000
  - id: SM_POC_MULTIPLE_METHOD|01.00.0000
    name: SM POC Multiple Method
    revision: 12
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-21T07:22:44.783+0000
  - id: SM_READ_FILE_SHIP_CONFIR|01.00.0000
    name: SM Read File Ship Confirm
    revision: 18
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-08T06:05:37.658+0000
  - id: SM_STRING_JS|01.00.0000
    name: SM String Js
    revision: 39
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-27T00:41:56.532+0000
  - id: SYNC_CUSTOMER_DETAILS|01.00.0000
    name: Sync Customer Details
    revision: 3
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-10T03:36:12.036+0000
  - id: TEST2|01.00.0000
    name: TEST2
    revision: 0
    updatedBy: cychew@knextech.com
    updatedDate: 2024-07-18T05:08:58.046+0000
  - id: TEST_S|01.00.0000
    name: test sy
    revision: 1
    updatedBy: syusop@knextech.com
    updatedDate: 2024-08-03T04:05:33.130+0000
  schedules:
  - id: KNX_IMPORT_AP_INVOICE|01.00.0000
    name: Schedule_BILL_IMPORT_AP_INVOICE_01_00_0000
    revision: 0
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-15T06:53:23.030+0000
  certificates:
  - id: USER|PGP|PUBLIC|PGP_PUBLIC_KEY
    name: PGP_PUBLIC_KEY
    revision: 0
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-15T06:52:06.723+0000
  connections:
  - id: HELLO_REST
    name: Hello REST
    revision: 0
    updatedBy: cychew@knextech.com
    updatedDate: 2024-07-18T02:40:55.129+0000
  - id: KGM_HCM_REST
    name: KGM HCM REST
    revision: 0
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-23T07:41:08.445+0000
  - id: KNX_ATP
    name: KNX ATP
    revision: 2
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-16T23:54:00.080+0000
  - id: KNX_BI_REPORT_SERVICE
    name: KNX BI Report Service
    revision: 5
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-20T02:51:59.820+0000
  - id: KNX_ERP_REST
    name: KNX ERP REST
    revision: 4
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-20T03:32:27.759+0000
  - id: KNX_FTP
    name: KNX FTP
    revision: 4
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-20T02:58:42.413+0000
  - id: KNX_GENERI_SOAP_PORT_SERVIC
    name: KNX Generic Soap Port Service
    revision: 0
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-15T07:00:47.802+0000
  - id: KNX_GITHUB
    name: KNX Github
    revision: 9
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-27T06:06:24.784+0000
  - id: KNX_GITHUB_TRIGGER
    name: KNX Github Trigger
    revision: 1
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-27T06:15:43.647+0000
  - id: KNX_OIC_REST
    name: KNX OIC REST
    revision: 0
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-20T00:53:15.824+0000
  - id: MONROVIA_ERP
    name: KNX ERP
    revision: 4
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-20T03:38:47.154+0000
  - id: MY_REST_ENDPOINT_INTERFAC
    name: Sample REST Endpoint Interface
    revision: 0
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-15T07:00:47.804+0000
  - id: TRIGGER1
    name: Trigger1
    revision: 2
    updatedBy: vbcsuser2@knextech.com
    updatedDate: 2024-08-09T08:12:17.042+0000
  lookups:
  - id: lookupEmail
    name: lookupEmail
    revision: 0
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-21T06:38:02.101+0000
  - id: lookupFTP
    name: lookupFTP
    revision: 1
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-06-21T03:49:16.661+0000
  eventtypes:
  - id: ERROREVENT|1
    name: ErrorEvent
  - id: ERROREVENT|2
    name: ErrorEvent
  - id: SERVICEREQUESTCREATED|5
    name: Create AP Invoice Event
  - id: SERVICEREQUESTCREATED|2
    name: ServiceRequestCreated
  - id: SERVICEREQUESTCREATED|3
    name: ServiceRequestCreated
  - id: SERVICEREQUESTCREATED|6
    name: Create AP Invoice Event
  - id: SERVICEREQUESTCREATED|1
    name: ServiceRequestCreated
  - id: SERVICEREQUESTCREATED|4
    name: ServiceRequestCreated
  libraries:
  - id: AZTEST|01.00.0000
    name: aztest
    revision: 21
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-27T03:33:13.478+0000
  - id: CHECKSTATUS|01.00.0000
    name: CheckStatus
    revision: 1
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-15T03:17:32.186+0000
  - id: DATECONVERSION|01.00.0000
    name: DateConversion
    revision: 1
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-21T04:09:33.037+0000
  - id: DATE_CONVERSION|01.00.0000
    name: Date Conversion
    revision: 0
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-15T06:53:23.031+0000
  - id: DATE_CONVERSION_METHOD|01.00.0000
    name: Date Conversion Method
    revision: 0
    updatedBy: cychew@knextech.com
    updatedDate: 2024-07-18T01:18:37.894+0000
  - id: GENERATEID|01.00.0000
    name: GenerateId
    revision: 0
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-14T08:20:53.887+0000
  - id: GENERATENUMBERNEW|01.00.0000
    name: generatenumberNew
    revision: 0
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-14T08:20:53.888+0000
  - id: GENERATEREFERALCODE|01.00.0000
    name: GenerateReferalCode
    revision: 0
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-14T08:20:53.888+0000
  - id: GETDATE|01.00.0000
    name: GetDate
    revision: 1
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-14T23:56:23.053+0000
  - id: GRANDTOTAL|01.00.0000
    name: GrandTotal
    revision: 1
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-15T03:50:47.399+0000
  - id: INPUTFORMAT|01.00.0000
    name: inputFormat
    revision: 3
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-21T08:00:45.131+0000
  - id: INPUTPOSITION|01.00.0000
    name: InputPosition
    revision: 1
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-15T04:13:02.120+0000
  - id: MULTIPLE|01.00.0000
    name: multiple
    revision: 101
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-27T00:58:48.854+0000
  - id: MYADD|01.00.0000
    name: myAdd
    revision: 8
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-23T01:42:41.920+0000
  - id: MYFUNCTION|01.00.0000
    name: myFunction
    revision: 44
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-24T02:17:20.672+0000
  - id: MYFUNCTIONDATE|01.00.0000
    name: myFunctionDate
    revision: 5
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-24T03:05:48.030+0000
  - id: MYFUNCTIONSTRING|01.00.0000
    name: myFunctionString
    revision: 15
    updatedBy: mariam.ismail@knextech.com
    updatedDate: 2024-08-27T00:31:54.908+0000
  - id: PARSEDATE|01.00.0000
    name: parseDate
    revision: 1
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-23T01:08:31.736+0000
  - id: REPLACESTRING|01.00.0000
    name: ReplaceString
    revision: 0
    updatedBy: syusop@knextech.com
    updatedDate: 2024-06-15T06:53:23.030+0000
  - id: REPLACESTRINGNEW|01.00.0000
    name: ReplaceStringNew
    revision: 3
    updatedBy: nabilasyraf.aidi@knextech.com
    updatedDate: 2024-08-15T04:49:18.704+0000
  labels:
  - id: DEPLOY1
    name: Deploy1
    revision: 1
    updatedBy: cychew@knextech.com
    updatedDate: 2024-07-24T01:24:56.829+0000
  - id: HELLOSY
    name: HelloSY
    revision: 1
    updatedBy: syusop@knextech.com
    updatedDate: 2024-08-21T05:56:29.256+0000
  - id: TESTAZ
    name: TestAZ
    revision: 1
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-21T07:34:06.262+0000
  - id: TESTDEPLOY
    name: testdeploy
    revision: 1
    updatedBy: azlinsafinar.asri@knextech.com
    updatedDate: 2024-08-22T00:29:08.761+0000
  rpa-flows:
  - id: TESTROBOT|01.00.0000
    name: testRobot
    updatedBy: syusop@knextech.com
    updatedDate: 1718782983966
  rpa-environmentPools:
  - id: TESTPOOL
    name: testPool
    updatedBy: syusop@knextech.com
    updatedDate: 1718783204310
origin:
  tenantOCID: ocid1.tenancy.oc1..aaaaaaaaq3kincdabv5oov23oretgafp7syoq4cuumowt43miazppan4teja
  serviceInstanceOCID: ocid1.integrationinstance.oc1.iad.amaaaaaaf277ujaarocljvpac2rp5l5yntht4pvvsq4c3qu3fs33ytkd2hea
