<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpInsertEmployee_REQUEST/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext nssrcmpr xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 nsmpr4 nsmpr5" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployee_REQUEST/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeDepartment_REQUEST/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeLocation_REQUEST/types" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeNumber_REQUEST/types" xmlns:nsmpr4="http://xmlns.oracle.com/cloud/adapter/REST/employee/types" xmlns:nsmpr5="http://www.oracle.com/2014/03/ic/integration/metadata">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/employee_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_45">
            <oracle-xsl-mapper:schema location="../../processor_111/resourcegroup_118/generated.wsdl" xml:id="id_46"/>
            <oracle-xsl-mapper:rootElement name="Employes" namespace="http://xmlns.oracle.com/cloud/adapter/REST/employee/types" xml:id="id_47"/>
            <oracle-xsl-mapper:param name="currEmployee" xml:id="id_48"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_77">
            <oracle-xsl-mapper:schema location="../../application_75/inbound_76/resourcegroup_77/atpSelectEmployee_REQUEST.wsdl" xml:id="id_78"/>
            <oracle-xsl-mapper:rootElement name="EmployeeCollection" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployee_REQUEST/types" xml:id="id_79"/>
            <oracle-xsl-mapper:param name="atpSelectEmployee" xml:id="id_80"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_81">
            <oracle-xsl-mapper:schema location="../../application_92/inbound_93/resourcegroup_94/atpSelectEmployeeDepartment_REQUEST.wsdl" xml:id="id_82"/>
            <oracle-xsl-mapper:rootElement name="EmployeeCollection" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeDepartment_REQUEST/types" xml:id="id_83"/>
            <oracle-xsl-mapper:param name="atpSelectEmployeeDepartment" xml:id="id_84"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_85">
            <oracle-xsl-mapper:schema location="../../application_92/inbound_93/resourcegroup_94/atpSelectEmployeeDepartment_REQUEST.wsdl" xml:id="id_86"/>
            <oracle-xsl-mapper:rootElement name="atpSelectEmployeeDepartmentSelect_DepartmentNameInputParameters" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeDepartment_REQUEST/types" xml:id="id_87"/>
            <oracle-xsl-mapper:param name="atpSelectEmployeeDepartment_REQUEST" xml:id="id_88"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_89">
            <oracle-xsl-mapper:schema location="../../application_124/inbound_125/resourcegroup_126/atpSelectEmployeeLocation_REQUEST.wsdl" xml:id="id_90"/>
            <oracle-xsl-mapper:rootElement name="EmployeeCollection" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeLocation_REQUEST/types" xml:id="id_91"/>
            <oracle-xsl-mapper:param name="atpSelectEmployeeLocation" xml:id="id_92"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_93">
            <oracle-xsl-mapper:schema location="../../application_124/inbound_125/resourcegroup_126/atpSelectEmployeeLocation_REQUEST.wsdl" xml:id="id_94"/>
            <oracle-xsl-mapper:rootElement name="atpSelectEmployeeLocationSelect_statusInputParameters" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeLocation_REQUEST/types" xml:id="id_95"/>
            <oracle-xsl-mapper:param name="atpSelectEmployeeLocation_REQUEST" xml:id="id_96"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_97">
            <oracle-xsl-mapper:schema location="../../application_37/inbound_38/resourcegroup_39/atpSelectEmployeeNumber_REQUEST.wsdl" xml:id="id_98"/>
            <oracle-xsl-mapper:rootElement name="EmployeeCollection" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeNumber_REQUEST/types" xml:id="id_99"/>
            <oracle-xsl-mapper:param name="atpSelectEmployeeNumber" xml:id="id_100"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_101">
            <oracle-xsl-mapper:schema location="../../application_37/inbound_38/resourcegroup_39/atpSelectEmployeeNumber_REQUEST.wsdl" xml:id="id_102"/>
            <oracle-xsl-mapper:rootElement name="atpSelectEmployeeNumberSelect_EmployeeNumberInputParameters" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployeeNumber_REQUEST/types" xml:id="id_103"/>
            <oracle-xsl-mapper:param name="atpSelectEmployeeNumber_REQUEST" xml:id="id_104"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_105">
            <oracle-xsl-mapper:schema location="../../application_75/inbound_76/resourcegroup_77/atpSelectEmployee_REQUEST.wsdl" xml:id="id_106"/>
            <oracle-xsl-mapper:rootElement name="atpSelectEmployeeSelectInputParameters" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployee_REQUEST/types" xml:id="id_107"/>
            <oracle-xsl-mapper:param name="atpSelectEmployee_REQUEST" xml:id="id_108"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_109">
            <oracle-xsl-mapper:schema location="../../processor_1/resourcegroup_2/ICSIntegrationMetadata.xsd" xml:id="id_110"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_111"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_112"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_194/inbound_195/resourcegroup_196/atpInsertEmployee_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="EmployeeCollection" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpInsertEmployee_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="currEmployee" xml:id="id_61"/>
   <xsl:param name="atpSelectEmployee" xml:id="id_113"/>
   <xsl:param name="atpSelectEmployeeDepartment" xml:id="id_114"/>
   <xsl:param name="atpSelectEmployeeDepartment_REQUEST" xml:id="id_115"/>
   <xsl:param name="atpSelectEmployeeLocation" xml:id="id_116"/>
   <xsl:param name="atpSelectEmployeeLocation_REQUEST" xml:id="id_117"/>
   <xsl:param name="atpSelectEmployeeNumber" xml:id="id_118"/>
   <xsl:param name="atpSelectEmployeeNumber_REQUEST" xml:id="id_119"/>
   <xsl:param name="atpSelectEmployee_REQUEST" xml:id="id_120"/>
   <xsl:param name="self" xml:id="id_121"/>
   <xsl:param name="tracking_var_1" xml:id="id_122"/>
   <xsl:param name="tracking_var_2" xml:id="id_123"/>
   <xsl:param name="tracking_var_3" xml:id="id_124"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:EmployeeCollection xml:id="id_12">
         <nstrgmpr:Employee xml:id="id_66">
            <nstrgmpr:employeeNumber xml:id="id_67">
               <xsl:value-of xml:id="id_68" select="$currEmployee/nsmpr4:Employes/nsmpr4:EmployeeNumber"/>
            </nstrgmpr:employeeNumber>
            <nstrgmpr:employeeName xml:id="id_69">
               <xsl:value-of xml:id="id_70" select="$currEmployee/nsmpr4:Employes/nsmpr4:EmployeeName"/>
            </nstrgmpr:employeeName>
            <nstrgmpr:employeeEmail xml:id="id_71">
               <xsl:value-of xml:id="id_72" select="$currEmployee/nsmpr4:Employes/nsmpr4:EmployeeEmail"/>
            </nstrgmpr:employeeEmail>
            <nstrgmpr:departmentNumber xml:id="id_73">
               <xsl:value-of xml:id="id_74" select="$currEmployee/nsmpr4:Employes/nsmpr4:Department/nsmpr4:DepartmentNumber"/>
            </nstrgmpr:departmentNumber>
            <nstrgmpr:status xml:id="id_75">
               <xsl:value-of xml:id="id_76" select="$currEmployee/nsmpr4:Employes/nsmpr4:Status"/>
            </nstrgmpr:status>
         </nstrgmpr:Employee>
      </nstrgmpr:EmployeeCollection>
   </xsl:template>
</xsl:stylesheet>