<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet xmlns:nssrcmpr="http://www.oracle.com/2014/03/ics/schedule" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/stagefile/writeCustomerDetailsStage_REQUEST/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/list/pull" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/ftp/listFileFTP_REQUEST/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/ftp/moveToArchive_REQUEST/types" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/ftp/readCustomerDetails_REQUEST/types" xmlns:nsmpr4="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns24="http://xmlns.oracle.com/cloud/adapter/ftp/readCustomerDetails_REQUEST/types/dynamicftp" xmlns:ns22="http://TargetNamespace.com/fileReference/readCustomerDetails" xmlns:ns26="http://xmlns.oracle.com/cloud/adapter/stagefile/writeCustomerDetailsStage/types" xmlns:nsmpr5="http://TargetNamespace.com/fileReference/writeStatusStage" version="2.0" xml:id="id_1" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 nsmpr4 nsmpr5" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace">
        <oracle-xsl-mapper:schema xml:id="id_2">
              <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
              <oracle-xsl-mapper:mapSources xml:id="id_3">
                    <oracle-xsl-mapper:source type="XSD" xml:id="id_4">
                          <oracle-xsl-mapper:schema location="../../processor_8/resourcegroup_9/ICSSchedule_1.xsd" xml:id="id_5"/>
                          <oracle-xsl-mapper:rootElement name="schedule" namespace="http://www.oracle.com/2014/03/ics/schedule" xml:id="id_6"/>
                    </oracle-xsl-mapper:source>
                    <oracle-xsl-mapper:source type="WSDL" xml:id="id_33">
                          <oracle-xsl-mapper:schema location="../../application_68/inbound_69/resourcegroup_70/readCustomerDetails_REQUEST.wsdl" xml:id="id_34"/>
                          <oracle-xsl-mapper:rootElement name="SyncReadFileResponse" namespace="http://xmlns.oracle.com/cloud/adapter/ftp/readCustomerDetails_REQUEST/types" xml:id="id_35"/>
                          <oracle-xsl-mapper:param name="readCustomerDetails" xml:id="id_36"/>
                    </oracle-xsl-mapper:source>
              </oracle-xsl-mapper:mapSources>
              <oracle-xsl-mapper:mapTargets xml:id="id_7">
                    <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
                          <oracle-xsl-mapper:schema location="../../processor_139/resourcegroup_140/writeCustomerDetailsStage_REQUEST.wsdl" xml:id="id_9"/>
                          <oracle-xsl-mapper:rootElement name="Write" namespace="http://xmlns.oracle.com/cloud/adapter/stagefile/writeCustomerDetailsStage_REQUEST/types" xml:id="id_10"/>
                    </oracle-xsl-mapper:target>
              </oracle-xsl-mapper:mapTargets>
        </oracle-xsl-mapper:schema>
        <xsl:param name="readCustomerDetails" xml:id="id_51"/>
        <xsl:template match="/" xml:id="id_11">
              <nstrgmpr:Write xml:id="id_12">
                    <ns26:request-wrapper>
                          <xsl:for-each-group select="$readCustomerDetails/nsmpr3:SyncReadFileResponse/ns24:FileReadResponse/ns22:Customers/ns22:Customer" group-by="ns22:Customer_Number">
                                <ns26:topLevelArray>
                                      <ns26:SourceSystem>
                                            <xsl:value-of select="ns22:Source_System"/>
                                      </ns26:SourceSystem>
                                      <ns26:CustomerNumber>
                                            <xsl:value-of select="ns22:Customer_Number"/>
                                      </ns26:CustomerNumber>
                                      <ns26:CustomerSourceReference>
                                            <xsl:value-of select="ns22:Customer_Source_Reference"/>
                                      </ns26:CustomerSourceReference>
                                      <ns26:CustomerName>
                                            <xsl:value-of select="ns22:Customer_Name"/>
                                      </ns26:CustomerName>
                                      <ns26:D-U-N-SNumber>
                                            <xsl:value-of select="ns22:D-U-N-S_Number"/>
                                      </ns26:D-U-N-SNumber>
                                      <ns26:TaxpayerID>
                                            <xsl:value-of select="ns22:Taxpayer_ID"/>
                                      </ns26:TaxpayerID>
                                      <ns26:TaxpayerRegistrationNumber>
                                            <xsl:value-of select="ns22:Taxpayer_Registration_Number"/>
                                      </ns26:TaxpayerRegistrationNumber>
                                      <ns26:CustomerGSAIndicator>
                                            <xsl:value-of select="ns22:Customer_GSA_Indicator"/>
                                      </ns26:CustomerGSAIndicator>
                                      <xsl:for-each-group select="fn:current-group()" group-by="ns22:Account_Number">
                                            <ns26:Account>
                                                  <ns26:AccountNumber>
                                                        <xsl:value-of select="ns22:Account_Number"/>
                                                  </ns26:AccountNumber>
                                                  <ns26:AccountSourceReference>
                                                        <xsl:value-of select="ns22:Account_Source_Reference"/>
                                                  </ns26:AccountSourceReference>
                                                  <ns26:AccountDescription>
                                                        <xsl:value-of select="ns22:Account_Description"/>
                                                  </ns26:AccountDescription>
                                                  <ns26:AccountType>
                                                        <xsl:value-of select="ns22:Account_Type"/>
                                                  </ns26:AccountType>
                                                  <ns26:AccountEstablishedDate>
                                                        <xsl:value-of select="ns22:Account_Established_Date"/>
                                                  </ns26:AccountEstablishedDate>
                                                  <ns26:CustomerClass>
                                                        <xsl:value-of select="ns22:Customer_Class"/>
                                                  </ns26:CustomerClass>
                                                  <ns26:CustomerProfileClass>
                                                        <xsl:value-of select="ns22:Customer_Profile_Class"/>
                                                  </ns26:CustomerProfileClass>
                                                  <xsl:for-each-group select="fn:current-group()" group-by="ns22:Site_Number">
                                                        <ns26:Site_Details>
                                                              <ns26:SiteNumber>
                                                                    <xsl:value-of select="ns22:Site_Number"/>
                                                              </ns26:SiteNumber>
                                                              <ns26:SiteSourceReference>
                                                                    <xsl:value-of select="ns22:Site_Source_Reference"/>
                                                              </ns26:SiteSourceReference>
                                                              <ns26:SiteName>
                                                                    <xsl:value-of select="ns22:Site_Name"/>
                                                              </ns26:SiteName>
                                                              <ns26:AccountAddressSet>
                                                                    <xsl:value-of select="ns22:Account_Address_Set"/>
                                                              </ns26:AccountAddressSet>
                                                              <ns26:LocationSourceReference>
                                                                    <xsl:value-of select="ns22:Location_Source_Reference"/>
                                                              </ns26:LocationSourceReference>
                                                              <ns26:AddressLine1>
                                                                    <xsl:value-of select="ns22:Address_Line_1"/>
                                                              </ns26:AddressLine1>
                                                              <ns26:AddressLine2>
                                                                    <xsl:value-of select="ns22:Address_Line_2"/>
                                                              </ns26:AddressLine2>
                                                              <ns26:MailStop>
                                                                    <xsl:value-of select="ns22:Mail_Stop"/>
                                                              </ns26:MailStop>
                                                              <ns26:AddressLine3>
                                                                    <xsl:value-of select="ns22:Address_Line_3"/>
                                                              </ns26:AddressLine3>
                                                              <ns26:AddressLine4>
                                                                    <xsl:value-of select="ns22:Address_Line_4"/>
                                                              </ns26:AddressLine4>
                                                              <ns26:Building>
                                                                    <xsl:value-of select="ns22:Building"/>
                                                              </ns26:Building>
                                                              <ns26:FloorNumber>
                                                                    <xsl:value-of select="ns22:Floor_Number"/>
                                                              </ns26:FloorNumber>
                                                              <ns26:TypeofHouse>
                                                                    <xsl:value-of select="ns22:Type_of_House"/>
                                                              </ns26:TypeofHouse>
                                                              <ns26:AdditionalAddressAttribute1>
                                                                    <xsl:value-of select="ns22:Additional_Address_Attribute_1"/>
                                                              </ns26:AdditionalAddressAttribute1>
                                                              <ns26:AdditionalAddressAttribute2>
                                                                    <xsl:value-of select="ns22:Additional_Address_Attribute_2"/>
                                                              </ns26:AdditionalAddressAttribute2>
                                                              <ns26:AdditionalAddressAttribute3>
                                                                    <xsl:value-of select="ns22:Additional_Address_Attribute_3"/>
                                                              </ns26:AdditionalAddressAttribute3>
                                                              <ns26:AdditionalAddressAttribute4>
                                                                    <xsl:value-of select="ns22:Additional_Address_Attribute_4"/>
                                                              </ns26:AdditionalAddressAttribute4>
                                                              <ns26:AdditionalAddressAttribute5>
                                                                    <xsl:value-of select="ns22:Additional_Address_Attribute_5"/>
                                                              </ns26:AdditionalAddressAttribute5>
                                                              <ns26:City>
                                                                    <xsl:value-of select="ns22:City"/>
                                                              </ns26:City>
                                                              <ns26:State>
                                                                    <xsl:value-of select="ns22:State"/>
                                                              </ns26:State>
                                                              <ns26:Province>
                                                                    <xsl:value-of select="ns22:Province"/>
                                                              </ns26:Province>
                                                              <ns26:PostalCode>
                                                                    <xsl:value-of select="ns22:Postal_Code"/>
                                                              </ns26:PostalCode>
                                                              <ns26:PostalCodeExtension>
                                                                    <xsl:value-of select="ns22:Postal_Code_Extension"/>
                                                              </ns26:PostalCodeExtension>
                                                              <ns26:County>
                                                                    <xsl:value-of select="ns22:County"/>
                                                              </ns26:County>
                                                              <ns26:Country>
                                                                    <xsl:value-of select="ns22:Country"/>
                                                              </ns26:Country>
                                                              <ns26:PhoneticAddressLine>
                                                                    <xsl:value-of select="ns22:Phonetic_Address_Line"/>
                                                              </ns26:PhoneticAddressLine>
                                                              <ns26:AddressDescription>
                                                                    <xsl:value-of select="ns22:Address_Description"/>
                                                              </ns26:AddressDescription>
                                                              <ns26:ShortDescription>
                                                                    <xsl:value-of select="ns22:Short_Description"/>
                                                              </ns26:ShortDescription>
                                                              <ns26:TimeZoneCode>
                                                                    <xsl:value-of select="ns22:Time_Zone_Code"/>
                                                              </ns26:TimeZoneCode>
                                                              <ns26:SalesTaxGeocode>
                                                                    <xsl:value-of select="ns22:Sales_Tax_Geocode"/>
                                                              </ns26:SalesTaxGeocode>
                                                              <ns26:SalesTaxInsideCityLimits>
                                                                    <xsl:value-of select="ns22:Sales_Tax_Inside_City_Limits"/>
                                                              </ns26:SalesTaxInsideCityLimits>
                                                              <ns26:IdentifyingAddress>
                                                                    <xsl:value-of select="ns22:Identifying_Address"/>
                                                              </ns26:IdentifyingAddress>
                                                              <ns26:SiteLanguage>
                                                                    <xsl:value-of select="ns22:Site_Language"/>
                                                              </ns26:SiteLanguage>
                                                              <ns26:TranslatedCustomerName>
                                                                    <xsl:value-of select="ns22:Translated_Customer_Name"/>
                                                              </ns26:TranslatedCustomerName>
                                                              <xsl:for-each select="fn:current-group()">
                                                                    <ns26:Site_Uses>
                                                                          <ns26:SitePurposeSourceReference>
                                                                                <xsl:value-of select="ns22:Site_Purpose_Source_Reference"/>
                                                                          </ns26:SitePurposeSourceReference>
                                                                          <ns26:Purpose>
                                                                                <xsl:value-of select="ns22:Purpose"/>
                                                                          </ns26:Purpose>
                                                                          <ns26:SitePurposePrimaryIndicator>
                                                                                <xsl:value-of select="ns22:Site_Purpose_Primary_Indicator"/>
                                                                          </ns26:SitePurposePrimaryIndicator>
                                                                          <ns26:Site>
                                                                                <xsl:value-of select="ns22:Site"/>
                                                                          </ns26:Site>
                                                                          <ns26:Bill-toSite>
                                                                                <xsl:value-of select="ns22:Bill-to_Site"/>
                                                                          </ns26:Bill-toSite>
                                                                          <ns26:PaymentMethod>
                                                                                <xsl:value-of select="ns22:Payment_Method"/>
                                                                          </ns26:PaymentMethod>
                                                                          <ns26:PrimaryPaymentMethodIndicator>
                                                                                <xsl:value-of select="ns22:Primary_Payment_Method_Indicator"/>
                                                                          </ns26:PrimaryPaymentMethodIndicator>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldContextPrompt>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Context_Prompt"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldContextPrompt>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment1>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_1"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment1>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment2>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_2"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment2>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment3>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_3"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment3>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment4>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_4"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment4>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment5>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_5"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment5>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment6>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_6"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment6>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment7>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_7"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment7>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment8>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_8"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment8>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment9>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_9"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment9>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment10>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_10"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment10>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment11>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_11"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment11>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment12>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_12"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment12>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment13>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_13"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment13>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment14>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_14"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment14>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment15>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_15"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment15>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment16>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_16"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment16>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment17>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_17"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment17>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment18>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_18"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment18>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment19>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_19"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment19>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment20>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_20"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment20>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment21>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_21"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment21>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment22>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_22"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment22>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment23>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_23"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment23>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment24>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_24"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment24>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment25>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_25"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment25>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment26>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_26"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment26>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment27>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_27"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment27>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment28>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_28"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment28>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment29>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_29"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment29>
                                                                          <ns26:CustomerAccountDescriptiveFlexfieldSegment30>
                                                                                <xsl:value-of select="ns22:Customer_Account_Descriptive_Flexfield_Segment_30"/>
                                                                          </ns26:CustomerAccountDescriptiveFlexfieldSegment30>
                                                                    </ns26:Site_Uses>
                                                              </xsl:for-each>
                                                        </ns26:Site_Details>
                                                  </xsl:for-each-group>
                                            </ns26:Account>
                                      </xsl:for-each-group>
                                </ns26:topLevelArray>
                          </xsl:for-each-group>
                    </ns26:request-wrapper>
              </nstrgmpr:Write>
        </xsl:template>
  </xsl:stylesheet>