<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpInsertEmployee_REQUEST/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext nssrcmpr xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 nsmpr4 nsmpr5 nsmpr1" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpCreateEmployee_REQUEST/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectDepartment_REQUEST/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectEmployee_REQUEST/types" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectLocation_REQUEST/types" xmlns:nsmpr4="http://xmlns.oracle.com/cloud/adapter/REST/employee/types" xmlns:nsmpr5="http://www.oracle.com/2014/03/ic/integration/metadata">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/employee_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/employee_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_17">
            <oracle-xsl-mapper:schema location="../../application_295/inbound_296/resourcegroup_365/atpSelectDepartment_REQUEST.wsdl" xml:id="id_18"/>
            <oracle-xsl-mapper:rootElement name="DepartmentCollection" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpSelectDepartment_REQUEST/types" xml:id="id_19"/>
            <oracle-xsl-mapper:param name="atpSelectDepartment" xml:id="id_20"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_41">
            <oracle-xsl-mapper:schema location="../../processor_20/resourcegroup_27/generated.wsdl" xml:id="id_42"/>
            <oracle-xsl-mapper:rootElement name="createEmployeeRequest" namespace="http://xmlns.oracle.com/cloud/adapter/REST/employee/types" xml:id="id_43"/>
            <oracle-xsl-mapper:param name="currEmployee" xml:id="id_44"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_521/inbound_522/resourcegroup_523/atpInsertEmployee_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="EmployeeCollection" namespace="http://xmlns.oracle.com/cloud/adapter/atpdatabase/atpInsertEmployee_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="atpSelectDepartment" xml:id="id_50"/>
   <xsl:param name="currEmployee" xml:id="id_56"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:EmployeeCollection xml:id="id_12">
         <nstrgmpr:Employee xml:id="id_61">
            <nstrgmpr:employeeNumber xml:id="id_62">
               <xsl:value-of xml:id="id_63" select="$currEmployee/nsmpr4:createEmployeeRequest/nsmpr4:EmployeeNumber"/>
            </nstrgmpr:employeeNumber>
            <nstrgmpr:employeeName xml:id="id_64">
               <xsl:value-of xml:id="id_65" select="$currEmployee/nsmpr4:createEmployeeRequest/nsmpr4:EmployeeName"/>
            </nstrgmpr:employeeName>
            <nstrgmpr:employeeEmail xml:id="id_66">
               <xsl:value-of xml:id="id_67" select="$currEmployee/nsmpr4:createEmployeeRequest/nsmpr4:EmployeeEmail"/>
            </nstrgmpr:employeeEmail>
            <xsl:choose xml:id="id_77">
               <xsl:when xml:id="id_78" test="string-length ($atpSelectDepartment/nsmpr1:DepartmentCollection/nsmpr1:Department/nsmpr1:departmentNumber ) > 0">
                  <nstrgmpr:departmentNumber xml:id="id_79">
                     <xsl:value-of xml:id="id_82" select="$atpSelectDepartment/nsmpr1:DepartmentCollection/nsmpr1:Department/nsmpr1:departmentNumber"/>
                  </nstrgmpr:departmentNumber>
               </xsl:when>
               <xsl:otherwise xml:id="id_80">
                  <nstrgmpr:departmentNumber xml:id="id_81">
                     <xsl:value-of xml:id="id_83" select="$currEmployee/nsmpr4:createEmployeeRequest/nsmpr4:Department/nsmpr4:DepartmentNumber"/>
                  </nstrgmpr:departmentNumber>
               </xsl:otherwise>
            </xsl:choose>
            <nstrgmpr:status xml:id="id_68">
               <xsl:value-of xml:id="id_69" select="$currEmployee/nsmpr4:createEmployeeRequest/nsmpr4:Status"/>
            </nstrgmpr:status>
            <nstrgmpr:lastUser xml:id="id_70">
               <xsl:value-of xml:id="id_71" select="$currEmployee/nsmpr4:createEmployeeRequest/nsmpr4:LastUser"/>
            </nstrgmpr:lastUser>
            <nstrgmpr:createdBy xml:id="id_72">
               <xsl:value-of xml:id="id_73" select="$currEmployee/nsmpr4:createEmployeeRequest/nsmpr4:CreatedBy"/>
            </nstrgmpr:createdBy>
            <nstrgmpr:createdDate xml:id="id_74">
               <xsl:value-of xml:id="id_75" select="$currEmployee/nsmpr4:createEmployeeRequest/nsmpr4:CreatedDate"/>
            </nstrgmpr:createdDate>
         </nstrgmpr:Employee>
      </nstrgmpr:EmployeeCollection>
   </xsl:template>
</xsl:stylesheet>