<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://www.oracle.com/2014/03/ics/schedule" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/erp/findCustomerAccount_REQUEST/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 nsmpr4 nsmpr5 nsmpr6 nsmpr6" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/list/pull" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/ftp/readContactDetails/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/ftp/deleteFile_REQUEST/types" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/ftp/listFileFTP_REQUEST/types" xmlns:nsmpr4="http://xmlns.oracle.com/cloud/adapter/ftp/readContactDetails_REQUEST/types" xmlns:nsmpr5="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns36="http://xmlns.oracle.com/adf/svc/types/" xmlns:nsmpr6="http://TargetNamespace.com/fileReference">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="XSD" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../processor_8/resourcegroup_9/ICSSchedule_1.xsd" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="schedule" namespace="http://www.oracle.com/2014/03/ics/schedule" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_76">
            <oracle-xsl-mapper:schema location="../../processor_94/resourcegroup_386/generated.wsdl" xml:id="id_77"/>
            <oracle-xsl-mapper:rootElement name="Contact" namespace="http://TargetNamespace.com/fileReference" xml:id="id_78"/>
            <oracle-xsl-mapper:param name="currPerson" xml:id="id_79"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_117/inbound_118/resourcegroup_119/findCustomerAccount_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="findCustomerAccount" namespace="http://xmlns.oracle.com/cloud/adapter/erp/findCustomerAccount_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="currPerson" xml:id="id_110"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:findCustomerAccount xml:id="id_12">
         <nstrgmpr:findCriteria xml:id="id_62">
            <ns36:filter xml:id="id_63">
               <ns36:group xml:id="id_64">
                  <ns36:item xml:id="id_65">
                     <ns36:attribute xml:id="id_68">
                        <xsl:value-of xml:id="id_69" select="&quot;AccountNumber&quot;"/>
                     </ns36:attribute>
                     <ns36:operator xml:id="id_66">
                        <xsl:value-of xml:id="id_67" select="&quot;=&quot;"/>
                     </ns36:operator>
                     <ns36:value xml:id="id_70">
                        <xsl:value-of xml:id="id_71" select="$currPerson/nsmpr6:Contact/nsmpr6:Account_Number"/>
                     </ns36:value>
                  </ns36:item>
               </ns36:group>
            </ns36:filter>
         </nstrgmpr:findCriteria>
      </nstrgmpr:findCustomerAccount>
   </xsl:template>
</xsl:stylesheet>