<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/date_REQUEST/jsGetCurrentTimestamp/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://www.oracle.com/2014/03/ics/callout" xmlns:nsmpr1="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns25="http://xmlns.oracle.com/cloud/adapter/REST/date/jsGetCurrentTimestamp/types" xmlns:ns24="http://xml.oracle.com/types/REST/date_REQUEST/jsGetCurrentTimestamp">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_32/outbound_33/resourcegroup_34/date_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/date_REQUEST/jsGetCurrentTimestamp/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD" xml:id="id_13">
            <oracle-xsl-mapper:schema location="../../processor_54/resourcegroup_55/ICSCallout_Output.xsd" xml:id="id_14"/>
            <oracle-xsl-mapper:rootElement name="output_JavaScriptGetCurrentTimestamp_res" namespace="http://www.oracle.com/2014/03/ics/callout" xml:id="id_15"/>
            <oracle-xsl-mapper:param name="JavaScriptGetCurrentTimestamp" xml:id="id_16"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_17">
            <oracle-xsl-mapper:schema location="../../processor_68/resourcegroup_69/ICSCallout_Output.xsd" xml:id="id_18"/>
            <oracle-xsl-mapper:rootElement name="output_JavaScriptToDateOnly_res" namespace="http://www.oracle.com/2014/03/ics/callout" xml:id="id_19"/>
            <oracle-xsl-mapper:param name="JavaScriptToDateOnly" xml:id="id_20"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_21">
            <oracle-xsl-mapper:schema location="../../processor_100/resourcegroup_101/ICSCallout_Output.xsd" xml:id="id_22"/>
            <oracle-xsl-mapper:rootElement name="output_JavaScriptToISO_res" namespace="http://www.oracle.com/2014/03/ics/callout" xml:id="id_23"/>
            <oracle-xsl-mapper:param name="JavaScriptToISO" xml:id="id_24"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_25">
            <oracle-xsl-mapper:schema location="../../processor_59/resourcegroup_60/ICSCallout_Output.xsd" xml:id="id_26"/>
            <oracle-xsl-mapper:rootElement name="output_JavaScriptToLocalDate_res" namespace="http://www.oracle.com/2014/03/ics/callout" xml:id="id_27"/>
            <oracle-xsl-mapper:param name="JavaScriptToLocalDate" xml:id="id_28"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_29">
            <oracle-xsl-mapper:schema location="../../processor_89/resourcegroup_90/ICSCallout_Output.xsd" xml:id="id_30"/>
            <oracle-xsl-mapper:rootElement name="output_JavaScriptToTimezone_res" namespace="http://www.oracle.com/2014/03/ics/callout" xml:id="id_31"/>
            <oracle-xsl-mapper:param name="JavaScriptToTimezone" xml:id="id_32"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_32/outbound_33/resourcegroup_34/date_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/date_REQUEST/jsGetCurrentTimestamp/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="JavaScriptGetCurrentTimestamp" xml:id="id_37"/>
   <xsl:param name="JavaScriptToDateOnly" xml:id="id_38"/>
   <xsl:param name="JavaScriptToISO" xml:id="id_39"/>
   <xsl:param name="JavaScriptToLocalDate" xml:id="id_40"/>
   <xsl:param name="JavaScriptToTimezone" xml:id="id_41"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:executeResponse xml:id="id_12">
         <ns25:response-wrapper xml:id="id_46">
            <ns25:CurrentTimestamp xml:id="id_47">
               <xsl:value-of xml:id="id_48" select="$JavaScriptGetCurrentTimestamp/nsmpr0:output_JavaScriptGetCurrentTimestamp_res"/>
            </ns25:CurrentTimestamp>
            <ns25:LocalDate xml:id="id_53">
               <xsl:value-of xml:id="id_54" select="$JavaScriptToLocalDate/nsmpr0:output_JavaScriptToLocalDate_res"/>
            </ns25:LocalDate>
            <ns25:DateOnly xml:id="id_49">
               <xsl:value-of xml:id="id_50" select="$JavaScriptToDateOnly/nsmpr0:output_JavaScriptToDateOnly_res"/>
            </ns25:DateOnly>
            <ns25:OtherTimeZone xml:id="id_55">
               <xsl:value-of xml:id="id_56" select="concat (&quot;The timestamp for &quot;, /nstrgmpr:execute/nstrgmpr:QueryParameters/ns24:timeZone, &quot; timezone is &quot;, $JavaScriptToTimezone/nsmpr0:output_JavaScriptToTimezone_res )"/>
            </ns25:OtherTimeZone>
            <ns25:ISOFormat xml:id="id_51">
               <xsl:value-of xml:id="id_52" select="$JavaScriptToISO/nsmpr0:output_JavaScriptToISO_res"/>
            </ns25:ISOFormat>
         </ns25:response-wrapper>
      </nstrgmpr:executeResponse>
   </xsl:template>
</xsl:stylesheet>