<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://www.oracle.com/2014/03/ics/schedule" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/stagefile/writeStatusStage_REQUEST/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 nsmpr4 nsmpr5 nsmpr6 nsmpr1 nsmpr7 nsmpr7" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/list/pull" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/ftp/readContactDetails/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/ftp/deleteFile_REQUEST/types" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/erp/findCustomerAccount_REQUEST/types" xmlns:nsmpr4="http://xmlns.oracle.com/cloud/adapter/ftp/listFileFTP_REQUEST/types" xmlns:nsmpr5="http://xmlns.oracle.com/cloud/adapter/ftp/readContactDetails_REQUEST/types" xmlns:nsmpr6="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns43="http://TargetNamespace.com/fileReference/writeStatusStage" xmlns:nsmpr7="http://TargetNamespace.com/fileReference">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="XSD" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../processor_8/resourcegroup_9/ICSSchedule_1.xsd" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="schedule" namespace="http://www.oracle.com/2014/03/ics/schedule" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_53">
            <oracle-xsl-mapper:schema location="../../processor_13/resourcegroup_14/ICSIntegrationMetadata.xsd" xml:id="id_54"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_55"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_56"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_86">
            <oracle-xsl-mapper:schema location="../../processor_94/resourcegroup_386/generated.wsdl" xml:id="id_87"/>
            <oracle-xsl-mapper:rootElement name="Contact" namespace="http://TargetNamespace.com/fileReference" xml:id="id_88"/>
            <oracle-xsl-mapper:param name="currPerson" xml:id="id_89"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_125">
            <oracle-xsl-mapper:schema location="../../processor_47/resourcegroup_54/generated.wsdl" xml:id="id_126"/>
            <oracle-xsl-mapper:rootElement name="File" namespace="http://xmlns.oracle.com/cloud/list/pull" xml:id="id_127"/>
            <oracle-xsl-mapper:param name="currFile" xml:id="id_128"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_129">
            <oracle-xsl-mapper:schema location="../../application_79/inbound_80/resourcegroup_81/deleteFile_REQUEST.wsdl" xml:id="id_130"/>
            <oracle-xsl-mapper:rootElement name="DeleteFileResponse" namespace="http://xmlns.oracle.com/cloud/adapter/ftp/deleteFile_REQUEST/types" xml:id="id_131"/>
            <oracle-xsl-mapper:param name="deleteFile" xml:id="id_132"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_133">
            <oracle-xsl-mapper:schema location="../../application_79/inbound_80/resourcegroup_81/deleteFile_REQUEST.wsdl" xml:id="id_134"/>
            <oracle-xsl-mapper:rootElement name="DeleteFile" namespace="http://xmlns.oracle.com/cloud/adapter/ftp/deleteFile_REQUEST/types" xml:id="id_135"/>
            <oracle-xsl-mapper:param name="deleteFile_REQUEST" xml:id="id_136"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_137">
            <oracle-xsl-mapper:schema location="../../application_117/inbound_118/resourcegroup_119/findCustomerAccount_REQUEST.wsdl" xml:id="id_138"/>
            <oracle-xsl-mapper:rootElement name="findCustomerAccountResponse" namespace="http://xmlns.oracle.com/cloud/adapter/erp/findCustomerAccount_REQUEST/types" xml:id="id_139"/>
            <oracle-xsl-mapper:param name="findCustomerAccount" xml:id="id_140"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_141">
            <oracle-xsl-mapper:schema location="../../application_117/inbound_118/resourcegroup_119/findCustomerAccount_REQUEST.wsdl" xml:id="id_142"/>
            <oracle-xsl-mapper:rootElement name="findCustomerAccount" namespace="http://xmlns.oracle.com/cloud/adapter/erp/findCustomerAccount_REQUEST/types" xml:id="id_143"/>
            <oracle-xsl-mapper:param name="findCustomerAccount_REQUEST" xml:id="id_144"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_145">
            <oracle-xsl-mapper:schema location="../../application_32/inbound_33/resourcegroup_34/listFileFTP_REQUEST.wsdl" xml:id="id_146"/>
            <oracle-xsl-mapper:rootElement name="ListFileResponse" namespace="http://xmlns.oracle.com/cloud/adapter/ftp/listFileFTP_REQUEST/types" xml:id="id_147"/>
            <oracle-xsl-mapper:param name="listFileFTP" xml:id="id_148"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_149">
            <oracle-xsl-mapper:schema location="../../application_32/inbound_33/resourcegroup_34/listFileFTP_REQUEST.wsdl" xml:id="id_150"/>
            <oracle-xsl-mapper:rootElement name="ListFile" namespace="http://xmlns.oracle.com/cloud/adapter/ftp/listFileFTP_REQUEST/types" xml:id="id_151"/>
            <oracle-xsl-mapper:param name="listFileFTP_REQUEST" xml:id="id_152"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_153">
            <oracle-xsl-mapper:schema location="../../application_64/inbound_65/resourcegroup_66/readContactDetails_REQUEST.wsdl" xml:id="id_154"/>
            <oracle-xsl-mapper:rootElement name="SyncReadFileResponse" namespace="http://xmlns.oracle.com/cloud/adapter/ftp/readContactDetails_REQUEST/types" xml:id="id_155"/>
            <oracle-xsl-mapper:param name="readContactDetails" xml:id="id_156"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_157">
            <oracle-xsl-mapper:schema location="../../application_64/inbound_65/resourcegroup_66/readContactDetails_REQUEST.wsdl" xml:id="id_158"/>
            <oracle-xsl-mapper:rootElement name="SyncReadFile" namespace="http://xmlns.oracle.com/cloud/adapter/ftp/readContactDetails_REQUEST/types" xml:id="id_159"/>
            <oracle-xsl-mapper:param name="readContactDetails_REQUEST" xml:id="id_160"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../processor_325/resourcegroup_326/writeStatusStage_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="Write" namespace="http://xmlns.oracle.com/cloud/adapter/stagefile/writeStatusStage_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="self" xml:id="id_68"/>
   <xsl:param name="currPerson" xml:id="id_124"/>
   <xsl:param name="FTPPath" xml:id="id_165"/>
   <xsl:param name="currFile" xml:id="id_166"/>
   <xsl:param name="deleteFile" xml:id="id_167"/>
   <xsl:param name="deleteFile_REQUEST" xml:id="id_168"/>
   <xsl:param name="findCustomerAccount" xml:id="id_169"/>
   <xsl:param name="findCustomerAccount_REQUEST" xml:id="id_170"/>
   <xsl:param name="listFileFTP" xml:id="id_171"/>
   <xsl:param name="listFileFTP_REQUEST" xml:id="id_172"/>
   <xsl:param name="readContactDetails" xml:id="id_173"/>
   <xsl:param name="readContactDetails_REQUEST" xml:id="id_174"/>
   <xsl:param name="tracking_var_1" xml:id="id_176"/>
   <xsl:param name="tracking_var_2" xml:id="id_177"/>
   <xsl:param name="tracking_var_3" xml:id="id_178"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:Write xml:id="id_12">
         <ns43:StatusSet xml:id="id_72">
            <ns43:Status xml:id="id_73">
               <ns43:InstanceId xml:id="id_80">
                  <xsl:value-of xml:id="id_81" select="$self/nsmpr6:metadata/nsmpr6:runtime/nsmpr6:instanceId"/>
               </ns43:InstanceId>
               <ns43:Type xml:id="id_76">
                  <xsl:value-of xml:id="id_77" select="&quot;Customer Account&quot;"/>
               </ns43:Type>
               <ns43:Status xml:id="id_74">
                  <xsl:value-of xml:id="id_75" select="&quot;Error&quot;"/>
               </ns43:Status>
               <ns43:ErrorMessage xml:id="id_78">
                  <xsl:value-of xml:id="id_79" select="concat ($currPerson/nsmpr7:Contact/nsmpr7:Account_Number, &quot; is not exsit&quot; )"/>
               </ns43:ErrorMessage>
            </ns43:Status>
         </ns43:StatusSet>
      </nstrgmpr:Write>
   </xsl:template>
</xsl:stylesheet>